# Generated by Django 5.1.5 on 2025-01-30 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0003_customuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='room',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='user',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
