# Generated by Django 5.1.5 on 2025-03-08 00:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0009_booking_time_slot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='time_slot',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
    ]
