# Generated by Django 5.1.5 on 2025-03-21 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0011_booking_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
