# Generated by Django 5.1.5 on 2025-03-21 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0012_alter_booking_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='time_slot',
            field=models.DateTimeField(),
        ),
    ]
